<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <AssemblyName>wolle</AssemblyName>
    <RootNamespace>wolle</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);WPF0001</NoWarn>
  </PropertyGroup>

  

  <ItemGroup>
    <Resource Include="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.42.0" />
    <PackageReference Include="Neo.Markdig.Xaml" Version="1.0.10" />
  </ItemGroup>

</Project>